# Generated by Django 5.1.6 on 2025-02-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Risk_Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=100)),
                ("financial_stability", models.FloatField()),
                ("market_risk", models.FloatField()),
                ("operational_risk", models.FloatField()),
                ("compliance_risk", models.FloatField()),
                ("risk_score", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
