# Generated by Django 5.1.6 on 2025-02-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk_assessment",
            name="cybersecurity_risk",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="risk_assessment",
            name="reputation_risk",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="risk_assessment",
            name="supply_chain_risk",
            field=models.FloatField(default=0.5),
        ),
    ]
